### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by ragnorc** [cmdty/curves#10]
First of all, thank you very much for publishing this library, it is a great piece of work!
However, I am currently running into an 'out of memory' error (7 GB RAM available on machine) when executing the `max_smooth_interp` function for hourly data over 3 years. Is there any way this can be fixed without decreasing the length of the period or the granularity?

**Comment by cmdty** [comment]
Are you running in 32-bit or 64-bit Python? If 32-bit, switching up to 64-bit might fix this.

I am still a bit surprised with this error even in 32-bit Python, so if you email me the code I can take a closer look.

**Comment by ragnorc** [comment]
Thanks for your quick reply. It runs fine on my Mac but fails on GitHub Actions (need to run the script in CI).
The specifications of the GitHub machine are as follows:
2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

I emailed you the code :)

**Comment by cmdty** [comment]
Having thought about it a bit, the maximum smoothness spline implementation can be made much more memory efficient. I've created [a new issue](https://github.com/cmdty/curves/blob/master/docs/max_smoothness/max_smoothness_spline.pdf) which describes this enhancement.
