### ISSUE TITLE
Weird behaviour on last day of month

### ISSUE THREAD

**Issue by dr1012** [cmdty/curves#12]
First of all, thank you very much for creating this library. It's a very nifty tool! Great job! 
I'm seeing a weird behaviour when bootstrapping contracts that include days from multiple months:

`test_contracts = [

    (datetime.date(2020, 8, 24), datetime.date(2020, 8, 30), 10.0), 
    (datetime.date(2020, 8, 31), datetime.date(2020, 9, 6), 10.0),
    (datetime.date(2020, 9, 1), datetime.date(2020, 9, 30), 10.0)
]`

`piecewise_curve, bootstrapped_contracts = curves.bootstrap_contracts(test_contracts, freq='D')`

The generated bootstrapped contracts are the following, notice the very low value for 2020-08-31. 

`[Contract(start=Period('2020-08-24', 'D'), end=Period('2020-08-30', 'D'), price=10.000000000000002),
 Contract(start=Period('2020-08-31', 'D'), end=Period('2020-08-31', 'D'), price=1.724137931034483),
 Contract(start=Period('2020-09-01', 'D'), end=Period('2020-09-06', 'D'), price=11.379310344827585),
 Contract(start=Period('2020-09-07', 'D'), end=Period('2020-09-30', 'D'), price=9.655172413793101)]
`

![image](https://user-images.githubusercontent.com/33286856/90110546-4f3b7500-dd45-11ea-8969-19c331d37c9e.png)

The behaviour I would expect is for the contracts to all be equal to 10.0. Do you agree? Any ideas why the above is generated instead?

**Comment by cmdty** [comment]
Something certainly looks fishy there! I haven't got time to look at this right now, but this does remind me of a common annoying pitfall in this algorithm which you'll find discussed in another solution, which also has a bit of a hacky solution: https://github.com/cmdty/curves/issues/8

**Comment by dr1012** [comment]
Thank you very much! Agreed the solution is a bit hacky, but it works!

**Comment by cmdty** [comment]
@dr1012 I know it's a bit random, but I started looking at this problem again and think I have a solution, so watch this space!

But first, I have a questions for you. Do these contracts periods actually represent real inputs? I see you have 2 weeks, and a month+1 contract, but wouldn't there also be a Balance of Month contract prices, running from the 24th to the 31st?

Just adding the BOM contract isn't my "solution" (that is more mathematical), but I'm just interested in the real-world context in which this problem occurs.

**Comment by cmdty** [comment]
@dr1012 this issue has been fixed in version 1.1.0 of the curves Python package.
