### ISSUE TITLE
Bootstrapper issue when contracts are non-consecutive

### ISSUE THREAD

**Issue by jsenergy** [cmdty/curves#14]
Hello,

I have tried to build a quarterly peak curve using the input of one Cal value and two quarters. This unfortunately brings out NaN values in the output. See simplified code below.

Basic imports and European peak weighting (Monday-Friday) definitions:
```
from curves import bootstrap_contracts, max_smooth_interp, adjustments, weighting, contract_period

def pk_weight(period):
    if period.dayofweek < 5:
        return 1.0
    else:
        return 0.0
```
Defining peak contract for Q1-2022, Q3-2022 and  Cal-2022:
```
pk_cont = [(datetime.date(2022, 1, 1), datetime.date(2022, 3, 31), 75.71),
 (datetime.date(2022, 7, 1), datetime.date(2022, 9, 30), 47.56),
 (datetime.date(2022, 1, 1), datetime.date(2022, 12, 31), 60.65)]
```

Running bootstrapper to extrapolate Q2 and Q4 values:
```
q_peak_piecewise_curve, q_peak_bc_daily = bootstrap_contracts(pk_cont, freq='Q', average_weight=pk_weight)
```

The output is missing a Q4 value, which prevents me from running max_smooth_interp with a suitable mult_season_adjust to sort the shaping out on the final quarterly curve:

> 2022Q1    75.71
> 2022Q2    58.68
> 2022Q3    47.56
> 2022Q4      NaN
> Freq: Q-DEC, dtype: float64

My expectation is that it should generate two identical values for Q2 and Q4 (adjusted for peak hours in that contract). 

My initial suspicion was that the issue lies within the fact that 2022-12-31 is a Saturday and as such - despite the weighting function - the bootstrapper thinks it's an incomplete Q4 contract and therefore excludes it. 

To test, I tried using the following contract dates instead to no avail:
```
pk_cont = [(datetime.date(2022, 1, 3), datetime.date(2022, 3, 31), 75.71),
 (datetime.date(2022, 7, 1), datetime.date(2022, 9, 30), 47.56),
 (datetime.date(2022, 1, 3), datetime.date(2022, 12, 30), 60.65)]
```

Do you have any ideas how to work around this?

Regards

**Comment by cmdty** [comment]
This looks like it's caused by the same thing you had previously in [this issue](https://github.com/cmdty/curves/issues/9). You need to use a different weighting function for non-daily granularity as the one you've put above won't work. See the attached notebook in my response.

**Comment by jsenergy** [comment]
You are totally right. pk_weight() from above is only used for the dailies... Thanks for the quick response.
Works using:

```
def wd_weight(period):
    start = period.asfreq('B', 's')
    end = period.asfreq('B', 'e')
    return len(pd.period_range(start=start, end=end, freq='B'))
```

I have had this project on hold for a while but finally reviving it. I have some notes on some old code and there might be another real issue that I have...

Happily close this one however!
