### ISSUE TITLE
v1.0.3 is not Python 3.9 Compatible

### ISSUE THREAD

**Issue by Octiembre80** [cmdty/curves#18]
Please disregard if I misunderstood your documentation, as I believed 3.9 was supported as per below comment:

_The curves package is compatible with the Python interpreter up to version 3.9._

pythonnet-2.5.2 is not Python 3.9 compatible, only the pre-release is for now.

Error:
```
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet, curves
  Running setup.py install for pythonnet: started
  Running setup.py install for pythonnet: finished with status 'error'
  error: subprocess-exited-with-error

  Running setup.py install for pythonnet did not run successfully.
  exit code: 1

  [6 lines of output]
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: option --single-version-externally-managed not recognized
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

pythonnet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by cmdty** [comment]
Hi @Octiembre80 thanks for pointing this out. I've looked online and there is conflicting information about whether pythonnet 2.5.2 is compatible with Python 3.9. When I released curves version 1.0.2 it was working with Python 3.9. See the following image which shows pythonet 2.5.2 has installed property when running Python 3.9.12.
![image](https://user-images.githubusercontent.com/43233282/178912598-d2ed3f27-2c36-4475-a1ab-fc218134971c.png)

My guess is that pythonnet is compatible with some patch versions of Python 3.9.x.
