### ISSUE TITLE
Pip installation

### ISSUE THREAD

**Issue by crozo101** [cmdty/curves#19]
Keep encountering multiple errors when trying to install the package. 

" note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure." 

I have the correct packages installed (versions greater than these). 
pythonnet==2.5.2
setuptools==40.8.0
wheel==0.33.1
pandas>=1.0.3

Tried manually installing to the python Lib directory but I'm still not able to import the curves module (in either the python sheel, or Conda).

**Comment by crozo101** [comment]
This error when I try to import 

ModuleNotFoundError: No module named 'clr'

**Comment by cmdty** [comment]
Hi @crozo101 can you give more details about the error messages you are seeing? Also, what is you exact Python version?

**Comment by cmdty** [comment]
Closing issue as not enough details given.
