### ISSUE TITLE
How to define contracts with different profile?

### ISSUE THREAD

**Issue by aleave** [cmdty/curves#2]
I am trying to use the package to generate a power forward curve. How can I define a baseload (24 hours per day) and a peakload (12 hours per day from 8 to 20) contract with the same start and end date to pass to the bootstrap function? Explicitely setting the hour in the start and end date would not work if the peakload contract is longer than a day. E.g. a Peak Jan-20 contract would have all the 8 to 20 hours for Mon-Fri days in January 2020. To generate the forward curve I need to mix baseload and peakload contracts in the list of contracts passed to the bootstrap

**Comment by cmdty** [comment]
That's a good question which, as I understand it, results from the fact that you've got a set of contracts with heterogeneous average weighting functions. The way to approach this is as follows:
- Derive the set of off-peak contracts from the peak and baseload contracts. You'll have write the code for this yourself, but it just requires some basic linear algebra to derive the off-peak price from the associated peak and baseload price for a specific contract. Now you'll have three sets of contracts for baseload, peak and off-peak respectively.
- Discard the baseload set of contracts, and call the bootstrap function twice, once passing in just the peak contracts, once passing in the derived off-peak contracts. For each call use the average_weight parameter to define weighting differently for peak and off-peak. The result should be two sets of bootstrapped contracts for peak and off-peak.
- If you want to see the bootstrapped baseload contract price just derive this in your own code as a weighted average of the associated peak and off-peak contracts.

A similar approach could be used when calling the max_smooth_interp spline function.

Does this answer your question?

**Comment by aleave** [comment]
thanks for the quick answer. Yes, this is the approach I have been trying: the problem I am having with this method is that at the smoothing stage I end up with:

`peak_piecewise_daily, bc_peak_daily = bootstrap_contracts(peak_contracts, freq='D', shaping_ratios = peak_ratios) #TODO: add weekday weight
offpeak_piecewise_daily, bc_offpeak_daily = bootstrap_contracts(offpeak_contracts, freq='D', shaping_ratios = offpeak_ratios)
`
I don't know how to combine bc_peak_daily and bc_offpeak_daily in a single set of contracts to pass to max_smooth_interp. I could of course smooth them separately but this seems to destroy the arbitrage free condition once I combine the smoothed peak and smoothed offpeak curves
What would you suggest?

**Comment by cmdty** [comment]
I don’t believe calling max_smooth_interp twice, once for peak and once for off-peak, will break any arbitrage conditions. You can check by averaging back the outputs to the raw inputs and if there is any difference it represents an arbitrage opportunity and hence a bug in the code.

If you try this and find any such arbitrages then post the code on here and I’ll take a look.

**Comment by aleave** [comment]
thanks, I may have done something wrong then. I will look again at my code and give you an update.

**Comment by aleave** [comment]
I confirm that the method you suggested works. The issue comes when I am passing a shaping profile (multiplicative, day of the week in my case) as an argument to max_smooth_interp. This does not seem to preserve the original contract value. Is the shaping being applied even to constrained parts of the curve ?

**Comment by cmdty** [comment]
The shaping should be applied to all parts of the curve, but it should preserve the original input contract prices. If it isn’t then it sounds like a bug. Can you post the code which shows this behaviour?

**Comment by aleave** [comment]
I will try to post something later. Would that be true even if I have daily contracts in my input set of contracts? E..g I am quoting a daily Friday contract for next week but I am also passing max_smooth_interp a shaping coefficient for Fridays. Would the logic of the function understand that the first Friday must not be smoothed?

**Comment by cmdty** [comment]
Ah ok, now I understand your previous question. In the case where you’re building a daily curve, applying a daily multiplicative shaping, but an input contract exists for a single day, then the multiplicative shaping would essentially not be applied for this day. Actually, internally in the code it will be applied, but would then be cancelled out. This is necessary to preserve no-arbitrage with the input contracts.

**Comment by cmdty** [comment]
Am I good to close this issue now?

**Comment by aleave** [comment]
I do see some issue when using the smoothing: the combination of smoothed peak and smoothed offpeak does not give me a perfect arbitrage free curve, I see values off by 1-2% in certain cases. Unfortunately I am working with a case that is to complex to post as an example. I suggest you close the issue and I will eventually reopen it if I find the time to build a simple example.

**Comment by aleave** [comment]
I think the problem is the following: for the peak contract, the bootstrapping into daily gives you a daily series whose average is equal to the peak contract (e.g. for a month). But this is not correct: the bootstrapping should give you a series such that when you only consider business days the average is the peak contract. Otherwise when you combine offpeak and peak as suggested above, the result will not be consistent. The problem is that the bootstrapping function has no notion of "profile" at the moment, a contract is fully determined by start and end date + weighting but the output is always in calendar months/days/hours

**Comment by cmdty** [comment]
OK, I’ll take a look at this later today.

**Comment by cmdty** [comment]
@aleave I'm pretty sure there isn't a problem. You'll see that I've just pushed a [commit](https://github.com/cmdty/curves/commit/c411068a7366fac0c2e8e7a79f7b99c48073ea56) where I update one of the unit tests for bootstrap_contracts which asserts that the result averages back to input contracts using the specified average weighting function. Previously this test used an equal weighting of 1.0 for every day, but I updated this to use a weighting that could be for peak-load. The test still passed and I even debugged it to check that the calculations were happening as expected.

If you have a concrete case where there arbitrage opportunities are generated please post the code on GitHub so I can take a closer look.

**Comment by jsenergy** [comment]
First of all many thanks for the development of this package and apologies for reopening a closed issue.
@cmdty I am in a similar situation to  @aleave , trying to use curves to build European power forward curves. My approach is to build two separate curves; one peak (5x12h, 8am-8pm) and one off-peak (5x12h, 8pm-8am + 2x24h weekends).

For simplification, I am working with a daily curve to begin with but I am failing to get a zero-arb output. I am attaching a simplified workbook for you to have a look.

A follow-up complication when peak values get populated is that the max_smooth_interp function is affected.

Unfortunately, I am not an experienced programmer but with some guidance I am happy to do further testing to help figure this out.

[Peak optimisation.ipynb.zip](https://github.com/cmdty/curves/files/4369277/Peak.optimisation.ipynb.zip)

**Comment by cmdty** [comment]
Hi jsenergy, thanks for the example. I'll take a close look. I've reopened the issue, but won't be able to look at this until the weekend.

**Comment by jsenergy** [comment]
Perhaps the weighting function is part of the issue:

```
def weekday_weight(period):
    start_day = period.asfreq('B', 's')
    end_day = period.asfreq('B', 'e')
    return len(pd.period_range(start=start_day, end=end_day, freq='B'))
```

Take Week 15: April 6th to April 12th;

```
start = pd.Period(datetime.datetime(2020, 4, 6),'D')
end = pd.Period(datetime.datetime(2020, 4, 12),'D')
start_day = pd.Period(start).asfreq('B', 's')
end_day =  pd.Period(end).asfreq('B', 'e')

period = pd.period_range(start=start_day, end=end_day, freq='D')
len(period)
```

end_day actually becomes Period('2020-04-13', 'B'), meaning that the length of period is 6. However if I change the frequency from start to start, making the length of the period range 5 - consistent with the number of peak days in a week contract - the output still is not arb free.

**Comment by cmdty** [comment]
Hi @jsenergy, see the attached notebook, which is an amended version of the one that you provided. I've made two changes:
- I've change the weekday_weight function to one that actually works. Thanks for finding this problem! The old incorrect version of this function actually gives double the weight for weekends, so is actually an off-peak weight. I'll also update my sample notebook accordingly.
- I've commented out two input contracts which span over weekend periods, and as such cannot be valid peak contracts. In fact, with the amended weekday_weight function the bootstrap_contracts was throwing an exception for these two contracts as the weighting was zero for both.

Now if you look at the averages generated from df_curve_adj, the bootstrap average for Apr-20 is now 23.47, the same as the input.

[Peak optimisation.zip](https://github.com/cmdty/curves/files/4397085/Peak.optimisation.zip)

**Comment by jsenergy** [comment]
This resolves the peak averaging problem - thank you very much! 

At this stage I am only building daily curves. Will take some time before I get to an hourly setup but assuming the same logic should apply.

**Comment by cmdty** [comment]
@jsenergy I am planning on creating an example notebook for derivations of high-granularity power curve, but probably won't have time to do this for a while. In the meantime I can give you the following tips:
- Going from contract granularity to daily granularity in one step, and then from daily to hourly in a separate step is probably a good move. In fact how I've done this in the past is to derive the hourly price from the daily peak and offpeak prices using daily-to-hourly price scaling factors derived from a historical analysis, i.e. don't even use the spline. This is because I'm not sure the spline will give a "good" shape going to hourly granularity. One idea I did have, but never implemented, was to derive the price of 4-hour blocks from the daily prices, using historical shaping factors, and then use the spline to give from 4-hourly block granularity to hourly or half-hourly. The advantage of this approach is that it gets rid of some of the "noise" which you will no doubt find in hourly scaling factors.
- Another think to watch out for is that the daily curve derived from low granularity contracts, e.g. quarters, seasons, calendar years, often does not give a good shape. So it could be a good idea to first use the shaping factor functionality in the bootstrapper to derive monthly prices from your quaterly/seasonal/yearly prices first, before deriving the daily curve. Determining these scaling factors will probably require some sort of historical analysis.

**Comment by jsenergy** [comment]
Thanks for the tips @cmdty. To use the spline for 4h blocks seems like a sensible approach, which I had not considered. The rest is in line with how I had things laid out in my head.
